# Generated by Django 4.2 on 2023-11-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='Картинка')),
                ('text', models.CharField(max_length=100, verbose_name='Подпись')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factory', verbose_name='Фабрика')),
            ],
            options={
                'default_related_name': 'pictures',
            },
        ),
    ]
