# Generated by Django 4.2 on 2023-12-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('lat_coord', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('long_coord', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='factory_images/%Y/%m', verbose_name='Картинка завода')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m', verbose_name='Картинка')),
                ('text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factory', verbose_name='Фабрика')),
            ],
            options={
                'default_related_name': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.article', verbose_name='Следующая статья')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
