# Generated by Django 4.2 on 2023-12-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='is_factory',
            field=models.BooleanField(default=True),
        ),
    ]
